### PR TITLE
Project pages now display URLs properly

### PR DESCRIPTION
**Pull request by amandavisconti**
Thanks to Will for noticing!

### CODE REVIEW

**Comment by amandavisconti** [comment]
Please don't merge. I need to update /collection/work YAML from "url" to "website". URLs weren't displaying because YAML said `url:` but template said `link:`, and `page.url` is protected/already used for page's own URL. Choosing `website:` instead of `link:` because similar but I'm more sure the former is not a protected term, and it's early and I don't feel like researching that ¯\_(ツ)_/¯

**Comment by amandavisconti** [comment]
Others are very very welcome to look at this too, as I'm clearly not getting to this soon. I'm keeping the PR & associated issue open until we do, as it's got edits/adds to /work projects and also addresses something we do need to fix (URL display for projects)

**Comment by amandavisconti** [comment]
I have a task list item to try to fix this before launch, but am moving off the sprint project as it isn't launch-required.

**Comment by jeremyboggs** [comment]
Let's take a moment to review what the issue is, @amandavisconti? It's not clear to me what problem you're trying to address.

**Comment by amandavisconti** [comment]
Looks like I was just using `url: ` instead of `link: ` in some work YAML for some reason? I'll go through and fix that where it's happening. I have no idea what I was doing, and expect I was just missing the obvious there not being an issue.

**Pull request closed without merging**
