### PR TITLE
Zgl website sprint

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
# Description
Add description about what this pull request covers.
Little search bar in the nav and search results generating on each page. Still needs a lot of tweaking but wanted to know if we like the look of this or not...
## Number of Fixes
Type of number of fixes included in this PR.

## Related Ticket(s)
List related ticket(s) that apply to the work done in this pull request

----
(OPTIONAL)
#### Problem to Solve 
Describe the problem(s) this pull request solves.

#### Expected Behavior 
Describe the expected behavior.

#### Steps to Test Solution 

1. 

#### Testing (optional)

[ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
[ ] I certify that all existing tests pass

#### Documentation
[ ] There is new documentation in this pull request that must be reviewed..
[ ] I added documentation for any new classes/methods

#### Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

### CODE REVIEW

**Comment by ZoeLeBlanc** [comment]
@amandavisconti & @jeremyboggs do you mind pulling this down and letting me know if I'm going in the right direction with the search feature. I'm essentially copying what yale dh did [https://yaledhlab.github.io/dhlab-site/#](https://yaledhlab.github.io/dhlab-site/#)

**Comment by amandavisconti** [comment]
Looks good to me!

**Comment by ZoeLeBlanc** [comment]
Awesome! Thanks @amandavisconti . I'll continue building out the feature then 😄

**Comment by amandavisconti** [comment]
Okay to close this, or is there work in this branch that hasn't been merged yet?

**Comment by ZoeLeBlanc** [comment]
This branch is probably out of date at this point so I'm going to delete it.

**Pull request closed without merging**
