### PR TITLE
Events from WP

### PR DESCRIPTION
**Pull request by walshbr**
Refs #305 #363 #299 
 Work in progress for exporter.

### CODE REVIEW

**Comment by walshbr** [comment]
Def don't merge - going to open some related issues for tweaking the exporter. There is some massaging to be done before this is ready to load in.

**Comment by walshbr** [comment]
Pull on this @amandavisconti and see whatcha think? I think I got the data all there for archived events. I didn't pull over event drafts, FWIW. There are only six, and it seemed like it might make more sense to wait and pull over final content in one last sweep.

Note - the logic on the front page to pull out the upcoming / most recent three events is currently sorting on strings and not dates, so it's not working correctly. I'll open a separate issue for that so that we can close the couple other issues for events once this is merged. Also maybe worth noting that, since this is a static site, there isn't really a way to check for the current date unless we wanted to do some javascript-y thing that I'm not aware of. So the current logic just grabs the three events with the latest three timestamps, regardless of whether those events have happened or not.

**Comment by walshbr** [comment]
Will also close #418 when merged now.

**Comment by walshbr** [comment]
Also credit to @shane-et-al for helping with the script!

**Comment by amandavisconti** [comment]
I made a note in my final-content-sweep issue to check whether those WP event drafts were published and/or need migration to the main repo

**Pull request merged**
