### PR TITLE
Incorporate Student Projects Archive Into Our Work and Restructure Our Work

### LINKED ISSUE #626: Student data structure refactor?
right now every other data type we use is stored as a collection, and the student-project-archive stuff is the only one being stored in the _data folder

### LINKED ISSUE #627: Consider student projects archive vs. /Work page
We now have a separate /student-projects-archive page.

Do we want to:  
- [ ] Update individual project pages such that they cover everything the student-projects-archive items do (e.g. [recent] related blog posts)  
- [ ] Do we want to automatically pull new projects into this page if a student is listed as a project collaborator, or add some project metadata that will indicate if a project is student-led (and only pull those into the student archive page?)

Let's make sure these projects also show up on /work:
- [ ] Same as other projects, or highlight student work in a special section (or filter)?
- [ ] rather than having a standalone projects page, have this archive be a subsection of our work?
- [ ] see also #626

### PR DESCRIPTION
**Pull request by walshbr**
Closes #627
Closes #626
Refs #659 

This PR does a number of things:

It refactors the student projects archive so that they're structured the same as projects in Our Work
Creates a subsection on Our Work - one for non-student projects and one for student projects
Lists all student projects - including Praxis ones - on this subsection
Adjusts links on the For Students page accordingly
Adds "Related posts" to the work layout, so that if a project has posts associated with it it will pull those in.

The related posts can be passed a couple different ways - 

For projects that don't have a name per se you can just give it a yaml array with slugs in it like so in the header - 

posts: [hearing-silent-woolf, brandon-best-pr]

Or, for ongoing projects with a name and a ton of posts associated with them, you can add tags to associated blog posts. Note that this tag must match exactly the title of the project in question (i.e. Clockwork and ClockWork would be different projects). 

_layouts/work.html - line 26 has an array in which you'll need to add a new tag:

{% if page.title == 'Prism' or page.title == 'Ivanhoe' or page.title == 'ClockWork' or page.title == 'Dash-Amerikan' or page.title == 'UVA Reveal' or page.title == 'Neatline' %}

But this should be mergeable now. If a project doesn't have tagged posts they just won't get pulled into the project pages. So we can open a separate ticket for tagging posts in the future.

### CODE REVIEW

**Comment by amandavisconti** [comment]
This is excellent! One small bug: on /work, student projects that do have an associated image have zero image appear in the grid (the associated image appears fine on the actual specific project page):

Screen Shot 2019-07-04 at 9 29 43 AM

Looks like we'll need to fix this via lines 83-87 on pages/work.html; I didn't see an obvious fix but can look closer on a work day in the future.

**Comment by walshbr** [comment]
Ah good catch! Those images actually do exist in the repo - something weird must be going on with the how the path to the images are being made (I think it's just all the jpg's that are busted while the png files are working). I'll take a look next week - they all show up locally in the gallery for whatever reason.

**Comment by walshbr** [comment]
There was a relative_url filter being added in the layout - and the relative_url variable is set in the config to our domain. That means instead of our image paths being - 

/assets/img/whatever

they were

scholarslab.org/assets/img/whatever

So any image not on the server already came up as an error in the preview (but should have been fine on the live site) I'm not sure why you would want to hard generate URLs like that…the search results suggested it was for if your project is not in the root of your domain. So maybe it is more generally best practice but not required for our project? FWIW this is the third or fourth version of the same error - that relative_url filter pops up in a few places on our site, and I've just been taking them out as they cause unnecessary bugs. Should be good now if you check it again!

**Comment by jeremyboggs** [comment]
Happy to review this and merge, unless you'd still like to add a review @amandavisconti?

**Comment by amandavisconti** [comment]
@jeremyboggs No, please go ahead! Thanks!

**Comment by amandavisconti** [comment]
This looks great—I'll go ahead and merge it now

**Pull request merged**
