### PR TITLE
Reorganize directory structure to use a collections_dir

### LINKED ISSUE #350: File organization: set a collections directory in config.yml
## Situation:
- We have enough collections that they're getting crowded in the root folder
- Learned recently that Jekyll supports specifying a `collections_dir` variable in `_config.yml`

## Solution:
- Implement variable (probably just call it `collections` to match naming system for pages dir)

### PR DESCRIPTION
**Pull request by walshbr**
Closes #350. Required bumping the Jekyll version to 3.7. Tests run, and I clicked through things. All seemed to be working, but would be worth another pass. Also note that now our collection folders are no longer in the root, so documentation would need to be updated accordingly.

### CODE REVIEW

**Comment by walshbr** [comment]
I updated the rakefile, which is the only place I could think of that would touch the actual file structure before the page gets built. Documentation should be the other piece.

**Comment by amandavisconti** [comment]
I'll check this locally & try to resolve conflicts now

**Comment by amandavisconti** [comment]
Working on fixing failed check right now

**Comment by amandavisconti** [comment]
Looks like initial items in /_work (just the first item: augustcollecting), /_people (all current staff photos) are not displaying photos
_posts, _events, _spaces look fine, so must be specific to the grid display?

**Comment by amandavisconti** [comment]
YAYYYYYY

**Pull request merged**
