### PR TITLE
Zgl upgrade search

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
# Description
Add description about what this pull request covers.
This PR is for the implementation of the lunr search in the scholars lab site. We now have a pre-created search index from all the posts on the site. This PR uses lunr's latest immutable structure to create the index and hosts search results on the search page.

## Number of Fixes
Type of number of fixes included in this PR.
- number of fixes to gemfile, rakefile, new scripts, and js file

## Related Ticket(s)
List related ticket(s) that apply to the work done in this pull request
#2 #14 
----
(OPTIONAL)
#### Problem to Solve 
Describe the problem(s) this pull request solves.
Solves issue of no search 
#### Expected Behavior 
Describe the expected behavior.
You should be able to go to the search page and get search results for any query.  You can search by field, wildcard, or boost (more info [here in the lunr docs](https://lunrjs.com/guides/searching.html))
#### Steps to Test Solution 

1. Pull down my branch
2. bundle install
3. bundle exec jekyll build
4. bundle exec jekyll serve --watch
5. go to search on the site
6. search all you want 🎉

#### Testing (optional)

[ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
[ ] I certify that all existing tests pass

#### Documentation
[ ] There is new documentation in this pull request that must be reviewed..
[ ] I added documentation for any new classes/methods

#### Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

### CODE REVIEW

**Comment by jeremyboggs** [comment]
Thanks for this @ZoeLeBlanc! A few comments:

- I intentionally removed the 'minima' gem in 5aa3495ffbe9a8af846b61af7534fdd451366ba3. Did you need that theme for this? If not, mind rebasing to remove this gem?
-  Is there also a reason this branch includes that single blog post? From a quick glance, it looks  like the changes included there are superficial formatting things. But, if there are substantial changes in that post related to the search, could you say more? Otherwise, maybe rebase to not include that?

Also, what are your thoughts about expanding the search to all content? Would it be good to do that on your feature brach before merging, or do you think its good to merge and work on that on a new feature branch?

**Comment by ZoeLeBlanc** [comment]
@jeremyboggs sorry about the gems. I pulled down before you made the changes and then I must have screwed up the merge conflicts. I've pushed up the Gemfile and Gemfile.lock as matching your earlier commit. What blog post are you talking about? I'll play around with expanding the search.

**Comment by ZoeLeBlanc** [comment]
@jeremyboggs now have top level searching of pages as well as all posts 🎉 . Let me know if you want me to add research and people to the search as well.

**Comment by jeremyboggs** [comment]
@ZoeLeBlanc Lets' definitely add research and people, and events if we have some in there.

**Comment by ZoeLeBlanc** [comment]
@jeremyboggs so we can add other categories but we start hitting issues with front matter parsing. Should I take on the issue of meta-data normalization so that we can include different pages in the search?

**Comment by ZoeLeBlanc** [comment]
So we are now having only 237 errors on the travis ci. The majority are missing image assets with some issues to internal linking and missing http in links. I've also removed the node modules and now we're using lunr and moment js straight from CDNs. The final step will be figuring out a consistent metadata so that when lunr creates the search index it works for everything from posts to research to people.

**Comment by jeremyboggs** [comment]
@ZoeLeBlanc This looks good to me! It looks like there are a lot of changes on a number of content pages that correct URLs for things, right?

**Pull request merged**
