### PR TITLE
Adds library logotype to top bar.

### LINKED ISSUE #586: Add Library logo bar to top of site
Add different-colored bar along top of site, containing small UVA Library logo (above where top-left SLab logo is).

Amanda will tweet about the site when this is up.

### PR DESCRIPTION
**Pull request by jeremyboggs**
Fixes #586.

### CODE REVIEW

**Comment by walshbr** [comment]
Not sure why the netlify build is failing. The only thing I notice is that it's inconsistent across different pages that have different design backgrounds. Is that intentional? Or did you want to get rid of the white strip on the black background pages?
screen shot 2019-01-07 at 2 43 51 pm
screen shot 2019-01-07 at 2 43 43 pm

**Comment by walshbr** [comment]
@amandavisconti and @jeremyboggs - the Netlify preview was failing because the version of bundler we were using was in conflict with Netlify's version. I couldn't quite figure out how to solve this from our gemfile side, but I added a line to the Netlify build settings that resolves it for now. We might run into similar conflicts in the future, but patched at the moment. I retried your build, and should run through in a bit.

**Comment by amandavisconti** [comment]
I created #644 for the white strip issue @walshbr identified, but am going to push this because it is fine for launch.

**Comment by amandavisconti** [comment]
Merging resulted in a problem, so I reverted the merge but am not sure how to re-open this PR.

https://user-images.githubusercontent.com/899033/51109135-43cb4500-17c2-11e9-9b6d-e9bab3b9c83d.png

**Pull request merged**
